from __future__ import annotations

from pathlib import Path

path = Path(__file__).resolve().with_name("test_v121_proposal_baseline_regret.py")
text = path.read_text(encoding="utf-8")
old = '''    target_h = proposal_h.detach().clone()\n    target_v = proposal_v.detach().clone()\n    target_h[..., 0] = target_h[..., 0] + 0.25\n    target_v[..., 1] = target_v[..., 1] + 0.25\n    mask_h = torch.ones(proposal_h.shape[:-1], dtype=torch.float32)\n    mask_v = torch.ones(proposal_v.shape[:-1], dtype=torch.float32)\n'''
new = '''    mask_h = outputs["spline_graph_mask_h"][:, 0].detach().float()\n    mask_v = outputs["spline_graph_mask_v"][:, 0].detach().float()\n    assert float(mask_h.sum() + mask_v.sum()) > 0.0\n    target_h = proposal_h.detach().clone()\n    target_v = proposal_v.detach().clone()\n    # Perturb only true source-crossed edges. Non-crossing fractions are\n    # deliberately clamped and are outside the B1b same-edge teacher domain.\n    target_h[..., 0] = target_h[..., 0] + 0.25 * mask_h\n    target_v[..., 1] = target_v[..., 1] + 0.25 * mask_v\n'''
if text.count(old) != 1:
    raise RuntimeError(f"expected one gradient-probe block, found {text.count(old)}")
text = text.replace(old, new, 1)
old_tail = '''    geometry_head = model.geometry_net.production_structure.spline_graph.geometry_head\n    grad_total = sum(\n        float(parameter.grad.detach().abs().sum())\n        for parameter in geometry_head.parameters()\n        if parameter.grad is not None\n    )\n    assert grad_total > 0.0\n'''
new_tail = '''    geometry_head = model.geometry_net.production_structure.spline_graph.geometry_head\n    grad_total = sum(\n        float(parameter.grad.detach().abs().sum())\n        for parameter in geometry_head.parameters()\n        if parameter.grad is not None\n    )\n    if grad_total <= 0.0:\n        structure = model.geometry_net.production_structure\n        print("V12.1 diagnostic genome", structure.genome_dict())\n        print("V12.1 diagnostic masks", float(mask_h.sum()), float(mask_v.sum()))\n        print("V12.1 diagnostic proposal_requires_grad", proposal_h.requires_grad, proposal_v.requires_grad)\n        print("V12.1 diagnostic proposal_source_delta",\n              float(((proposal_h.detach() - source_h).abs() * mask_h[..., None]).sum()),\n              float(((proposal_v.detach() - source_v).abs() * mask_v[..., None]).sum()))\n        print("V12.1 diagnostic geometry_head_trainable",\n              [parameter.requires_grad for parameter in geometry_head.parameters()])\n        last_bias = geometry_head[-1].bias\n        if bool(mask_h.any()):\n            index = torch.nonzero(mask_h > 0.5, as_tuple=False)[0]\n            selected = proposal_h[index[0], index[1], index[2], 0]\n        else:\n            index = torch.nonzero(mask_v > 0.5, as_tuple=False)[0]\n            selected = proposal_v[index[0], index[1], index[2], 1]\n        selected_grad = torch.autograd.grad(\n            selected, last_bias, retain_graph=True, allow_unused=True\n        )[0]\n        print("V12.1 diagnostic selected_point_grad_to_last_bias",\n              None if selected_grad is None else selected_grad.detach().cpu().tolist())\n    assert grad_total > 0.0\n'''
if text.count(old_tail) != 1:
    raise RuntimeError(f"expected one gradient-probe tail, found {text.count(old_tail)}")
path.write_text(text.replace(old_tail, new_tail, 1), encoding="utf-8")
print("adjusted V12.1 gradient probe to active spline edges with actuator diagnostics")
