from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
REFINER = ROOT / "tools/nsamdr/neural/v9/explicit_spline_refiner.py"
TEST = ROOT / "tools/nsamdr/tests/test_v121_refiner_telemetry_contract.py"

text = REFINER.read_text(encoding="utf-8")
old = '''            graph["spline_refiner_energy_before"] = zero\n            graph["spline_refiner_energy_after"] = zero\n            graph["spline_refiner_node_shift_rms_pixels"] = zero\n            graph["spline_refiner_steps"] = zero\n            return graph\n'''
new = '''            graph["spline_refiner_energy_before"] = zero\n            graph["spline_refiner_energy_after"] = zero\n            graph["spline_refiner_node_shift_rms_pixels"] = zero\n            graph["spline_refiner_steps"] = zero\n            graph["spline_refiner_node_source_error"] = zero\n            graph["spline_refiner_span_source_error"] = zero\n            return graph\n'''
count = text.count(old)
if count != 2:
    raise RuntimeError(f"expected both no-op and empty-topology telemetry exits, found {count}")
REFINER.write_text(text.replace(old, new), encoding="utf-8")

TEST.write_text('''from __future__ import annotations\n\nfrom pathlib import Path\nimport sys\n\nimport torch\n\nROOT = Path(__file__).resolve().parents[3]\nNEURAL = ROOT / "tools/nsamdr/neural"\nif str(NEURAL) not in sys.path:\n    sys.path.insert(0, str(NEURAL))\n\nREQUIRED = (\n    "spline_refiner_energy_before",\n    "spline_refiner_energy_after",\n    "spline_refiner_node_shift_rms_pixels",\n    "spline_refiner_steps",\n    "spline_refiner_node_source_error",\n    "spline_refiner_span_source_error",\n)\n\ndef _assert_zero_telemetry(graph):\n    for key in REQUIRED:\n        assert key in graph, key\n        assert torch.is_tensor(graph[key])\n        assert torch.isfinite(graph[key]).all()\n        assert float(graph[key].detach().cpu()) == 0.0\n\ndef _proposal(config):\n    from v9.spline_graph import ConnectedSplineGraph\n    feature_channels = int(getattr(config, "spline_graph_feature_channels", 64))\n    graph_impl = ConnectedSplineGraph(feature_channels, config)\n    source = torch.zeros((1, 1, 8, 8), dtype=torch.float32)\n    features = torch.zeros((1, feature_channels, 8, 8), dtype=torch.float32)\n    proposal = graph_impl.build_graph(\n        features, features, source, topology_scale=1.0, displacement_scale=1.0\n    )\n    return graph_impl, source, proposal\n\ndef test_noop_refiner_returns_complete_telemetry():\n    from v9 import V9Config\n    from v9.explicit_spline_refiner import ExplicitSplineGeometryRefiner\n    config = V9Config()\n    config.spline_refiner_steps = 0\n    graph_impl, source, proposal = _proposal(config)\n    result = ExplicitSplineGeometryRefiner(config)(graph_impl, proposal, source)\n    _assert_zero_telemetry(result)\n\ndef test_empty_topology_refiner_returns_complete_telemetry():\n    from v9 import V9Config\n    from v9.explicit_spline_refiner import ExplicitSplineGeometryRefiner\n    config = V9Config()\n    config.spline_refiner_steps = 3\n    graph_impl, source, proposal = _proposal(config)\n    assert float(proposal["spline_graph_mask_h"].sum() + proposal["spline_graph_mask_v"].sum()) == 0.0\n    result = ExplicitSplineGeometryRefiner(config)(graph_impl, proposal, source)\n    _assert_zero_telemetry(result)\n\ndef test_direct_production_forward_survives_empty_refiner_topology():\n    from v9 import FidelityResidualNetV9, V9Config\n    config = V9Config()\n    config.training_activation_checkpointing = False\n    config.spline_refiner_steps = 3\n    model = FidelityResidualNetV9(config).eval()\n    inputs = torch.zeros((1, 17, 32, 32), dtype=torch.float32)\n    with torch.no_grad():\n        outputs = model(inputs)\n    for key in ("albedo", "normal_xy", "material", "roughness", "emissive"):\n        assert key in outputs\n        assert torch.isfinite(outputs[key]).all()\n    for key in REQUIRED:\n        assert key in outputs\n        assert torch.isfinite(outputs[key]).all()\n''', encoding="utf-8")

print("applied V12.1 complete refiner telemetry contract")
