"""NSAMDR V9 production package.

Install the active compatibility/model contracts in dependency order, then the V13
SR-first authority. Historical modules remain only where V13 still depends on their
checkpoint/model behaviour; retired launchers are not imported here.
"""

from .local_boundary_production_contract import install_local_boundary_production_contract
install_local_boundary_production_contract()

from .authority_alignment_contract import install_authority_alignment_contract
install_authority_alignment_contract()

from .b1_production_objective_contract import install_b1_production_objective_contract
install_b1_production_objective_contract()

from .parallel_detail_contract import install_parallel_detail_contract
install_parallel_detail_contract()

from .parallel_detail_optimization_contract import install_parallel_detail_optimization_contract
install_parallel_detail_optimization_contract()

from .baseline_relative_specialist_contract import install_baseline_relative_specialist_contract
install_baseline_relative_specialist_contract()

from .parallel_specialist_fusion_contract import install_parallel_specialist_fusion_contract
install_parallel_specialist_fusion_contract()

from .parallel_specialist_training_contract import install_parallel_specialist_training_contract
install_parallel_specialist_training_contract()

from .parallel_specialist_arbitration_contract import install_parallel_specialist_arbitration_contract
install_parallel_specialist_arbitration_contract()

from .parallel_specialist_training_isolation_contract import (
    install_parallel_specialist_training_isolation_contract,
)
install_parallel_specialist_training_isolation_contract()

from .parallel_specialist_safety_contract import install_parallel_specialist_safety_contract
install_parallel_specialist_safety_contract()

from .parallel_specialist_geometry_training_contract import (
    install_parallel_specialist_geometry_training_contract,
)
install_parallel_specialist_geometry_training_contract()

from .sr_first_contract import install_sr_first_contract
install_sr_first_contract()

from .sr_first_quality_contract import install_sr_first_quality_contract
install_sr_first_quality_contract()

from .sr_first_quick_config_contract import install_sr_first_quick_config_contract
install_sr_first_quick_config_contract()

from .sr_first_generalization_contract import install_sr_first_generalization_contract
install_sr_first_generalization_contract()
