"""Compatibility facade for the composition-oriented evolutionary recovery package."""
from .evolution import (
    DEFAULT_GENOME,
    EVOLUTION_SCHEMA,
    GENOME_BOUNDS,
    GENOME_NAMES,
    CandidateEvaluator,
    CandidateResult,
    EvolutionResult,
    EvolutionaryRecoveryController,
    FailureDetector,
    FailureKind,
    Genome,
    GenomeRepository,
    PopulationGenerator,
    RavenSampleProvider,
    StructuralFitness,
    StructuralObjective,
    classify_failure,
)

__all__ = [
    "DEFAULT_GENOME",
    "EVOLUTION_SCHEMA",
    "GENOME_BOUNDS",
    "GENOME_NAMES",
    "CandidateEvaluator",
    "CandidateResult",
    "EvolutionResult",
    "EvolutionaryRecoveryController",
    "FailureDetector",
    "FailureKind",
    "Genome",
    "GenomeRepository",
    "PopulationGenerator",
    "RavenSampleProvider",
    "StructuralFitness",
    "StructuralObjective",
    "classify_failure",
]
